### PR TITLE
respond with response object instead of empty string

### PR DESCRIPTION
**Pull request by BenMorganIO**
While using the MadMimi gem, I discovered that I wanted to log the responses from MadMimi to ensure that things go smoothly. While doing this, I discovered a feature that seems to be missing:

``` ruby
user = User.find user_id
response = mad_mimi.add_to_list user.email, list, user.attributes

Logs::MadMimi.create body: response.body, user_id: user_id
# => NoMethodError:
#      undefined method `body' for " ":String
```

Here, as you can see, the response was a string who's content was a single space. Given that the gem is based on HTTParty (like most ruby API service gems), then it might be more beneficial to a ruby developer to receive a `HTTParty::Response` object instead of a `String` object.

This PR may also turn off the `:raise_exceptions` feature. Please review and let me know what you think would be the best code to get it back in the gem.

### CODE REVIEW

**Comment by BenMorganIO** [comment]
bump

**Comment by threadhead** [comment]
+1

**Comment by BenMorganIO** [comment]
@maximgladkov ?

**Comment by BenMorganIO** [comment]
casual bump

**Comment by Thembadev** [comment]
@BenMorganIO thanks for the contrib. I tested the changes in your commit, and they seems to be breaking other tests. So we are not able to merge at this time.

We can look into adding more descriptive responses, but in the mean time you can refer to the "Return Values" section of our README:
"In most cases, a return value of a single space indicates success."

Thanks

**Comment by BenMorganIO** [comment]
@Thembadev please reopen.

Having a return response with the object not only allows a developer to see a 200/201/204, but it gives them a context of what the response is.

I also log the response as well and since madmimi overwrites the response with a single space, this makes knowing how an API call went not very intuitive.

Also, a lot of people don't know that a return value is a single space. There's a lot of devs on my team that don't read readme's to gems added by other developers.

I was also bumping for active code review. Please read the comments to the PR; particularly the last paragraph.

**Pull request closed without merging**
